export type SkillGroup = { label: string; items: string[] };

export const skillGroups: SkillGroup[] = [
  {
    label: "Languages & Scripting",
    items: [
      "Python",
      "TypeScript",
      "JavaScript",
      "Java",
      "SQL",
      "Terraform (HCL)",
      "C#",
      "C",
      "C++",
      "Ruby",
      "Bash",
      "HTML",
      "CSS",
    ],
  },
  {
    label: "AI & LLM Engineering",
    items: [
      "Anthropic Claude",
      "Claude Code",
      "Anthropic API",
      "Model Context Protocol (MCP)",
      "Vertex AI",
      "Google Gemini",
      "OpenAI Platform",
      "GitHub Copilot",
      "Glean AI",
      "AI Evaluation Frameworks",
    ],
  },
  {
    label: "Cloud & Infrastructure",
    items: [
      "Google Cloud Platform",
      "Cloud Run",
      "Cloud Run Worker Pools",
      "Cloud Run Jobs",
      "Cloud Functions v2",
      "Pub/Sub",
      "Cloud Scheduler",
      "Secret Manager",
      "IAM",
      "Artifact Registry",
      "Cloud Logging",
      "Cloud Storage",
      "AWS",
      "Azure",
      "Power Platform",
      "Docker",
      "Terraform",
    ],
  },
  {
    label: "Frameworks & Server Technologies",
    items: [
      "FastAPI",
      "Flask",
      "Spring Boot",
      "Node.js",
      "React",
      "Next.js",
      "Angular",
      "NgRx",
      "Rails",
      "React Native",
      "Expo",
    ],
  },
  {
    label: "Databases",
    items: [
      "PostgreSQL",
      "pgvector",
      "Cloud SQL",
      "Firestore / Datastore",
      "Microsoft SQL Server",
      "Liquibase",
      "SSMS",
    ],
  },
  {
    label: "APIs, Networking & Security",
    items: [
      "REST API Design",
      "Swagger / OpenAPI",
      "OAuth 2.0",
      "OpenID Connect (OIDC)",
      "TLS/SSL",
      "VPC Networking",
      "Private Service Connect",
      "Amazon Cognito",
      "Postman",
    ],
  },
  {
    label: "Tooling & Collaboration",
    items: [
      "Git",
      "GitHub",
      "GitLab",
      "GitLab CI/CD",
      "Azure DevOps",
      "Jira",
      "Confluence",
      "Miro",
      "VS Code",
      "IntelliJ IDEA",
      "PyCharm",
      "Cursor",
    ],
  },
];
